[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to   = "/.netlify/functions/api"
status = 200
force = true

# keep this AFTER the /api/* rule
[[redirects]]
from = "/*"
to   = "/index.html"
status = 200
